language: python
python: 2.7
install:
  - sudo apt-get install build-essential autoconf automake libtool libtool-bin libjansson-dev
  - pip install cookiecutter
script: |
  set -e
  CURDIR=$PWD
  cd /tmp
  cookiecutter --no-input $CURDIR
  cd bootstrap
  ./autogen.sh
  ./configure
  make
  libtool execute src/bootstrap
  make distcheck
